Add GitHub action running tests
trussworks/unemployment-insurance-modernization-demo pull request #63
Opened 2023-05-01 15:56 UTC by kleinschmidtj

## Resolves #36 

Changes proposed in this pull request:

- Adds GitHub action for running unit tests
- Builds off the draft PR #62

2023-05-04 19:56 UTC, brandonlenz requested changes
One question to some infra reserve folks for their input.

I _would_ like to see the --coverage flag added, plus a couple other things noted as comments

2023-05-04 19:56 UTC, brandonlenz commented on .github/workflows/test.yml
> +      - uses: actions/checkout@v3
@ralren @rpdelaney thoughts on using v3 or pinning the versions here?

2023-05-04 19:56 UTC, brandonlenz commented on .github/workflows/test.yml
> +      - run: yarn test
```suggestion
      - run: yarn test --coverage
```

2023-05-04 19:56 UTC, brandonlenz commented on .github/workflows/test.yml
> +      - run: yarn test
Sicne we'll wanna check for code coverage once we  improve that, it'll be nice to go ahead and print it in CI

2023-05-04 19:56 UTC, brandonlenz commented on __mocks__/styleMock.js
I think you can delete this file

2023-05-04 19:56 UTC, brandonlenz commented on .github/workflows/test.yml
> +        uses: actions/setup-node@v3
I think you'll want these

```suggestion
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
```

2023-05-04 20:14 UTC, brandonlenz approved these changes
Thanks for taking care of that! 

I'm good to approve and move things along, though I do think pinning action versions is a good best practice.

Feel free to wait for Ryan or Ren to weigh in. We can also take that to slack and update in a separate PR. Your preference!

2023-05-08 14:16 UTC, rpdelaney commented on .github/workflows/test.yml
> +      - uses: actions/checkout@v3
Pinning to a specific hash version is considered _best_ practice since it gives you the opportunity to review all changes to the shared action before running it in your repo. Renovatebot should still send PRs for updates following the version scheme it finds here.

2023-05-08 14:20 UTC, kleinschmidtj commented on .github/workflows/test.yml
> +      - uses: actions/checkout@v3
Pinned the github action in https://github.com/trussworks/unemployment-insurance-modernization-demo/pull/63/commits/e2467ff22b989b3271b7e62840c5121d2fae537c

2023-05-08 14:20 UTC, merged

2023-05-08 14:20 UTC, kleinschmidtj commented on .github/workflows/test.yml
> +      - uses: actions/checkout@v3
Ah, thank you! @rpdelaney